/**
 * This file is automatically generated by the custom storyblok-types plugin. Do not modify it manually.
 */

export interface BasePage {
  body?: [];
}

export interface InspirationEntry {
  title?: string;
  content?: unknown;
  image?: unknown;
  author?: string;
}

export interface InspirationList {
  inspirationList?: InspirationListItem;
}

export interface InspirationListItem {
  description?: string;
  layout?: unknown;
  isFeatured?: unknown;
  title?: string;
  eyebrow?: string;
  linkTo?: unknown;
  icon?: unknown;
  image?: unknown;
}

export interface Quizz {
  question?: string;
  option1?: string;
  option2?: string;
  option3?: string;
  correctAnswer?: string;
}

export interface WorkExperience {
  job_title?: string;
  description?: unknown;
  quizz?: Quizz;
  employer?: string;
  period?: string;
  location?: string;
  treasure?: unknown;
}

export interface WorkExperienceList {
  workexperience?: WorkExperience;
}
