/**
 * This file is automatically generated by the custom storyblok-types plugin. Do not modify it manually.
 */

export interface Page {
  body?: [];
}

export interface Quizz {
  question?: string;
  option1?: string;
  option2?: string;
  option3?: string;
  correctAnswer?: string;
}

export interface WorkExperience {
  job_title?: string;
  description?: unknown;
  quizz?: Quizz;
  employer?: string;
  period?: string;
  location?: string;
  treasure?: unknown;
}

export interface WorkExperienceList {
  workexperience?: WorkExperience;
}

