name: Lint Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint check
        run: yarn lint

      - name: Fail if linting errors
        run: |
          if [[ `git diff --name-only origin/main | grep ".js$"` ]]; then
            echo "There are linting errors."
            exit 1
          fi
